---

- name: verificando o container que esta no ar
  stat:
    path: /etc/nginx/sites-enabled/green.conf
  register: vhost


- name: enviando site para green
  copy:
    src: /var/lib/jenkins/workspace/bluegreen-deploy/index.html
    dest: /var/lib/docker/volumes/green/_data/
  when: vhost.stat.exists == False


- name: enviando site para blue
  copy:
    src: /var/lib/jenkins/workspace/bluegreen-deploy/index.html
    dest: /var/lib/docker/volumes/blue/_data/
  when: vhost.stat.exists == True


- name: consultando ip do container green
  shell: "docker exec green hostname -I"
  when: vhost.stat.exists == False
  register: ipgreen


- name: consultando ip do container blue
  shell: "docker exec blue hostname -I"
  when: vhost.stat.exists == True
  register: ipblue


- name: criando template para o green
  template:
    src: templates/vhost_green
    dest: /etc/nginx/sites-enabled/green.conf
  when: vhost.stat.exists == False


- name: criando template para o blue
  template:
    src: templates/vhost_blue
    dest: /etc/nginx/sites-enabled/blue.conf
  when: vhost.stat.exists == True


- name: apagando ambiente green
  file:
    path: /etc/nginx/sites-enabled/green.conf
    state: absent
  when: vhost.stat.exists == True


- name: apagando ambiente blue
  file:
    path: /etc/nginx/sites-enabled/blue.conf
    state: absent
  when: vhost.stat.exists == False


- name: realizando restart
  service:
    name: nginx
    state: restarted


